export const RECEIPT_SCHEMA: 'dagit-proof/v2';
export const LEGACY_RECEIPT_SCHEMA: 'dagit-proof/v1';
export const HASH_ALGORITHM: 'sha-256';
export const RECORD_KINDS: readonly ['original', 'revision', 'final', 'evidence'];
export type ProofRecord = { kind: 'original' | 'revision' | 'final' | 'evidence'; label: string; parent: { digest: `0x${string}`; manifestDigest: `0x${string}` } | null };
export type Receipt = { schema: 'dagit-proof/v2'; hashing: { algorithm: 'sha-256'; digest: `0x${string}`; byteLength: number }; record: ProofRecord; manifestDigest: `0x${string}`; chain?: { chainId: number; registry: string; transactionHash: string; blockNumber: string; blockHash: string; registrant: string; confirmations: number }; acknowledgement?: { signer: string; signature: `0x${string}`; signedAt: string } } | { schema: 'dagit-proof/v1'; hashing: { algorithm: 'sha-256'; digest: `0x${string}`; byteLength: number }; manifestDigest: `0x${string}`; chain?: { chainId: number; registry: string; transactionHash: string; blockNumber: string; blockHash: string; registrant: string; confirmations: number }; acknowledgement?: never };
export function normaliseDigest(digest: string): `0x${string}`;
export function digestBytes(bytes: Uint8Array): `0x${string}`;
export function canonicalManifest(value: { digest: string; byteLength: number; schema?: string; record?: Partial<ProofRecord> }): string;
export function manifestDigest(value: { digest: string; byteLength: number; schema?: string; record?: Partial<ProofRecord> }): `0x${string}`;
export function createUnsignedReceipt(value: { digest: string; byteLength: number; record?: Partial<ProofRecord> }): Extract<Receipt, { schema: 'dagit-proof/v2' }>;
export function verifyReceiptAgainstDigest(receipt: unknown, digest: string, byteLength: number): { ok: true; manifestDigest: `0x${string}` } | { ok: false; reason: string };
export function receiptIsValid(receipt: unknown): boolean;
export function portableProofFragment(receipt: Receipt): string;
export function receiptFromPortableFragment(fragment: string): Receipt | null;
export function acknowledgementTypedData(receipt: Receipt, signer: string, signedAt: string): { domain: { name: string; version: string; chainId: number; verifyingContract: string }; types: { ProofAcknowledgement: readonly { name: string; type: string }[] }; primaryType: string; message: { manifestDigest: `0x${string}`; transactionHash: `0x${string}`; signedAt: string }; signer: string };
export function verifyReceiptAcknowledgement(receipt: Receipt): Promise<{ ok: boolean; signer?: string; reason?: string }>;
