import { createRemoteJWKSet, jwtVerify } from "jose";

type Identity = { id: string; subject: string; email: string };
type Membership = { role: string; status: string };
const now = () => new Date().toISOString();
const text = (value: unknown, max: number, required = false) => { if (typeof value !== "string") { if (required) throw new Error("A required field is missing."); return ""; } const clean = value.trim(); if ((required && !clean) || clean.length > max) throw new Error("A field has an invalid length."); return clean; };
const json = (value: unknown, status = 200, requestId = crypto.randomUUID()) => new Response(JSON.stringify(value), { status, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store", "x-request-id": requestId, "x-content-type-options": "nosniff" } });
const digest = async (value: string) => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)))).map((byte) => byte.toString(16).padStart(2, "0")).join("");
const isDigest = (value: unknown) => typeof value === "string" && /^0x[0-9a-fA-F]{64}$/.test(value);
const forbidden = new Set(["file", "filename", "mime", "content", "bytes", "data", "document"]);
const rejectsDocument = (value: unknown): boolean => !value || typeof value !== "object" ? false : Array.isArray(value) ? value.some(rejectsDocument) : Object.entries(value as Record<string, unknown>).some(([key, child]) => forbidden.has(key.toLowerCase()) || rejectsDocument(child));
async function input(request: Request) { const parsed: unknown = await request.json(); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed) || rejectsDocument(parsed)) throw new Error("Only proof metadata is accepted."); return parsed as Record<string, unknown>; }
async function accessIdentity(request: Request, env: Env): Promise<{ subject: string; email: string }> {
  const token = request.headers.get("Cf-Access-Jwt-Assertion"); if (!token) throw new Error("Cloudflare Access authentication is required.");
  const keys = createRemoteJWKSet(new URL(`${env.ACCESS_TEAM_DOMAIN}/cdn-cgi/access/certs`));
  const { payload } = await jwtVerify(token, keys, { issuer: env.ACCESS_TEAM_DOMAIN, audience: env.ACCESS_AUD });
  const subject = typeof payload.sub === "string" ? payload.sub : ""; const email = typeof payload.email === "string" ? payload.email.toLowerCase() : "";
  if (!subject || !email) throw new Error("Access identity is incomplete."); return { subject, email };
}
async function identity(request: Request, env: Env, allowCreate = false): Promise<Identity> {
  const access = await accessIdentity(request, env); let row = await env.DB.prepare("SELECT id, idp_subject, email FROM identities WHERE idp_subject = ? AND status = 'active'").bind(access.subject).first<{id:string;idp_subject:string;email:string}>();
  if (!row) row = await env.DB.prepare("SELECT id, idp_subject, email FROM identities WHERE email = ? AND status = 'active'").bind(access.email).first<{id:string;idp_subject:string;email:string}>();
  if (!row && allowCreate) { const id = crypto.randomUUID(); await env.DB.prepare("INSERT INTO identities (id, idp_subject, email, created_at, updated_at) VALUES (?, ?, ?, ?, ?)").bind(id, access.subject, access.email, now(), now()).run(); return { id, ...access }; }
  if (!row) throw new Error("You do not yet belong to an organisation. Accept an organisation invitation first.");
  if (row.idp_subject !== access.subject) await env.DB.prepare("UPDATE identities SET idp_subject = ?, updated_at = ? WHERE id = ?").bind(access.subject, now(), row.id).run();
  return { id: row.id, ...access };
}
async function member(env: Env, actor: Identity, organisationId: string, roles?: string[]): Promise<Membership> { const row = await env.DB.prepare("SELECT role, status FROM organisation_memberships WHERE organisation_id = ? AND identity_id = ? AND status = 'active'").bind(organisationId, actor.id).first<Membership>(); if (!row || (roles && !roles.includes(row.role))) throw new Error("You do not have permission for this organisation."); return row; }
async function audit(env: Env, actor: Identity, organisationId: string, action: string, requestId: string, workspaceId?: string) { const previous = await env.DB.prepare("SELECT event_digest FROM organisation_audit_events WHERE organisation_id = ? ORDER BY occurred_at DESC LIMIT 1").bind(organisationId).first<{event_digest:string}>(); const occurredAt = now(); const id = crypto.randomUUID(); const eventDigest = await digest(`${id}|${organisationId}|${workspaceId ?? ""}|${actor.id}|${action}|${occurredAt}|${requestId}|${previous?.event_digest ?? ""}`); await env.DB.prepare("INSERT INTO organisation_audit_events (id, organisation_id, workspace_id, actor_identity_id, action, request_id, occurred_at, previous_event_digest, event_digest) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)").bind(id, organisationId, workspaceId ?? null, actor.id, action, requestId, occurredAt, previous?.event_digest ?? null, eventDigest).run(); }
function receipt(value: unknown) { if (!value || typeof value !== "object" || Array.isArray(value) || rejectsDocument(value)) throw new Error("A valid proof receipt is required."); const r = value as Record<string, unknown>; const hashing = r.hashing as Record<string, unknown> | undefined; const chain = r.chain as Record<string, unknown> | undefined; if (!hashing || !chain || !isDigest(hashing.digest) || !isDigest(r.manifestDigest) || !isDigest(chain.transactionHash)) throw new Error("Only anchored DAGIT proof receipts can be saved."); const serialized = JSON.stringify(value); if (serialized.length > 65536) throw new Error("Proof receipt is too large."); return { serialized, digest: hashing.digest as string, manifest: r.manifestDigest as string, tx: chain.transactionHash as string }; }

export async function handleOrganisationApi(request: Request, env: Env, ctx: ExecutionContext): Promise<Response | null> {
  const url = new URL(request.url); if (!url.pathname.startsWith("/firm/api/v2/")) return null; const requestId = crypto.randomUUID();
  try {
    if (request.method === "POST" && url.pathname === "/firm/api/v2/platform/organisations") {
      const actor = await identity(request, env, true); if (actor.email !== env.PLATFORM_OPERATOR_EMAIL.toLowerCase()) return json({ error: "Platform operator access is required." }, 403, requestId);
      const body = await input(request); const name = text(body.legalName, 160, true); const slug = text(body.slug, 64, true).toLowerCase(); const domain = text(body.domain, 253, true).toLowerCase(); if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug) || !/^[a-z0-9.-]+\.[a-z]{2,}$/i.test(domain)) throw new Error("Organisation slug or domain is invalid."); const id = crypto.randomUUID(); const created = now(); await env.DB.batch([env.DB.prepare("INSERT INTO organisations (id, legal_name, slug, retention_days, created_at) VALUES (?, ?, ?, ?, ?)").bind(id, name, slug, Number(body.retentionDays) || 365, created), env.DB.prepare("INSERT INTO organisation_domains (organisation_id, domain) VALUES (?, ?)").bind(id, domain), env.DB.prepare("INSERT INTO organisation_memberships (organisation_id, identity_id, role, created_at) VALUES (?, ?, 'administrator', ?)").bind(id, actor.id, created)]); ctx.waitUntil(audit(env, actor, id, "organisation.provisioned", requestId)); return json({ organisation: { id, name, slug, domain, status: "active" } }, 201, requestId);
    }
    if (request.method === "POST" && url.pathname === "/firm/api/v2/invitations/accept") { const raw = await accessIdentity(request, env); const body = await input(request); const token = text(body.token, 200, true); const invitation = await env.DB.prepare("SELECT id, organisation_id, workspace_id, organisation_role, workspace_role FROM organisation_invitations WHERE token_digest = ? AND email = ? AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > ?").bind(await digest(token), raw.email, now()).first<{id:string;organisation_id:string;workspace_id:string|null;organisation_role:string;workspace_role:string|null}>(); if (!invitation) throw new Error("This invitation is invalid or expired."); const actor = await identity(request, env, true); const accepted = now(); await env.DB.batch([env.DB.prepare("INSERT OR IGNORE INTO organisation_memberships (organisation_id, identity_id, role, created_at) VALUES (?, ?, ?, ?)").bind(invitation.organisation_id, actor.id, invitation.organisation_role, accepted), ...(invitation.workspace_id && invitation.workspace_role ? [env.DB.prepare("INSERT OR IGNORE INTO workspace_memberships (workspace_id, identity_id, role, granted_by, granted_at) VALUES (?, ?, ?, ?, ?)").bind(invitation.workspace_id, actor.id, invitation.workspace_role, actor.id, accepted)] : []), env.DB.prepare("UPDATE organisation_invitations SET accepted_at = ? WHERE id = ?").bind(accepted, invitation.id)]); ctx.waitUntil(audit(env, actor, invitation.organisation_id, "invitation.accepted", requestId, invitation.workspace_id ?? undefined)); return json({ accepted: true }, 200, requestId); }
    const actor = await identity(request, env); if (request.method === "GET" && url.pathname === "/firm/api/v2/session") { const rows = await env.DB.prepare("SELECT o.id, o.legal_name as name, o.slug, om.role FROM organisations o JOIN organisation_memberships om ON om.organisation_id = o.id WHERE om.identity_id = ? AND om.status = 'active' AND o.status = 'active' ORDER BY o.created_at").bind(actor.id).all(); return json({ identity: { email: actor.email }, organisations: rows.results }, 200, requestId); }
    const orgMatch = url.pathname.match(/^\/firm\/api\/v2\/organisations\/([0-9a-f-]{36})(?:\/(.*))?$/); if (!orgMatch) return json({ error: "Not found." }, 404, requestId); const organisationId = orgMatch[1]; const tail = orgMatch[2] ?? "";
    if (request.method === "POST" && tail === "workspaces") { await member(env, actor, organisationId, ["administrator", "member"]); const body = await input(request); const id = crypto.randomUUID(); const created = now(); const type = text(body.type, 32, true); if (!["general","legal","contractor","property","personal"].includes(type)) throw new Error("Workspace type is invalid."); const alias = text(body.referenceAlias, 160, true); await env.DB.batch([env.DB.prepare("INSERT INTO workspaces (id, organisation_id, workspace_type, reference_alias, created_by, created_at) VALUES (?, ?, ?, ?, ?, ?)").bind(id, organisationId, type, alias, actor.id, created), env.DB.prepare("INSERT INTO workspace_memberships (workspace_id, identity_id, role, granted_by, granted_at) VALUES (?, ?, 'manager', ?, ?)").bind(id, actor.id, actor.id, created)]); ctx.waitUntil(audit(env, actor, organisationId, "workspace.created", requestId, id)); return json({ workspace: { id, type, referenceAlias: alias, status: "open" } }, 201, requestId); }
    if (request.method === "GET" && tail === "workspaces") { await member(env, actor, organisationId); const rows = await env.DB.prepare("SELECT w.id, w.workspace_type as type, w.reference_alias as referenceAlias, w.status, wm.role, w.created_at as createdAt FROM workspaces w JOIN workspace_memberships wm ON wm.workspace_id = w.id AND wm.identity_id = ? AND wm.revoked_at IS NULL WHERE w.organisation_id = ? AND w.status != 'deleted' ORDER BY w.created_at DESC LIMIT 100").bind(actor.id, organisationId).all(); return json({ workspaces: rows.results }, 200, requestId); }
    const workspaceMatch = tail.match(/^workspaces\/([0-9a-f-]{36})(?:\/(.*))?$/);
    if (workspaceMatch) {
      const workspaceId = workspaceMatch[1]; const workspaceTail = workspaceMatch[2] ?? "";
      await member(env, actor, organisationId);
      const permission = await env.DB.prepare("SELECT wm.role, w.status FROM workspaces w JOIN workspace_memberships wm ON wm.workspace_id = w.id AND wm.identity_id = ? AND wm.revoked_at IS NULL WHERE w.id = ? AND w.organisation_id = ?").bind(actor.id, workspaceId, organisationId).first<{role:string;status:string}>();
      if (!permission) throw new Error("This workspace is not available to you.");
      if (request.method === "POST" && workspaceTail === "proofs") { if (!['manager','contributor'].includes(permission.role) || permission.status !== 'open') throw new Error("You cannot add a proof to this workspace."); const body = await input(request); const stage = text(body.stage, 20, true); if (!['recorded','revision','final','handover','inspection','delivery'].includes(stage)) throw new Error("Proof stage is invalid."); const value = receipt(body.receipt); const id = crypto.randomUUID(); await env.DB.prepare("INSERT INTO workspace_proofs (id, workspace_id, stage, receipt_json, digest, manifest_digest, chain_tx, created_by, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)").bind(id, workspaceId, stage, value.serialized, value.digest, value.manifest, value.tx, actor.id, now()).run(); ctx.waitUntil(audit(env, actor, organisationId, "proof.saved", requestId, workspaceId)); return json({ proof: { id, stage } }, 201, requestId); }
      if (request.method === "POST" && workspaceTail === "members") { if (permission.role !== 'manager') throw new Error("Only a workspace manager can add a member."); const body = await input(request); const identityId = text(body.identityId, 36, true); const role = text(body.role, 20, true); if (!['manager','contributor','reader'].includes(role)) throw new Error("Workspace role is invalid."); const orgMember = await env.DB.prepare("SELECT 1 FROM organisation_memberships WHERE organisation_id = ? AND identity_id = ? AND status = 'active'").bind(organisationId, identityId).first(); if (!orgMember) throw new Error("The person is not an active organisation member."); await env.DB.prepare("INSERT INTO workspace_memberships (workspace_id, identity_id, role, granted_by, granted_at, revoked_at) VALUES (?, ?, ?, ?, ?, NULL) ON CONFLICT(workspace_id, identity_id) DO UPDATE SET role = excluded.role, granted_by = excluded.granted_by, granted_at = excluded.granted_at, revoked_at = NULL").bind(workspaceId, identityId, role, actor.id, now()).run(); ctx.waitUntil(audit(env, actor, organisationId, "workspace.member_granted", requestId, workspaceId)); return json({ granted: true }, 200, requestId); }
      if (request.method === "DELETE" && workspaceTail === "") { if (permission.role !== 'manager') throw new Error("Only a workspace manager can delete a workspace."); await env.DB.prepare("UPDATE workspaces SET status = 'deleted', deleted_at = ? WHERE id = ? AND organisation_id = ?").bind(now(), workspaceId, organisationId).run(); ctx.waitUntil(audit(env, actor, organisationId, "workspace.deleted", requestId, workspaceId)); return json({ deleted: true }, 200, requestId); }
    }
    if (request.method === "POST" && tail === "invitations") { await member(env, actor, organisationId, ["administrator"]); const body = await input(request); const token = crypto.randomUUID().replaceAll("-", "") + crypto.randomUUID().replaceAll("-", ""); const id = crypto.randomUUID(); const expires = new Date(Date.now() + 7 * 86400000).toISOString(); await env.DB.prepare("INSERT INTO organisation_invitations (id, organisation_id, workspace_id, email, organisation_role, workspace_role, token_digest, expires_at, created_by, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").bind(id, organisationId, text(body.workspaceId, 36) || null, text(body.email, 254, true).toLowerCase(), text(body.organisationRole, 20, true), text(body.workspaceRole, 20) || null, await digest(token), expires, actor.id, now()).run(); ctx.waitUntil(audit(env, actor, organisationId, "invitation.created", requestId)); return json({ invitation: { id, token, expiresAt: expires } }, 201, requestId); }
    if (request.method === "GET" && tail === "audit") { await member(env, actor, organisationId, ["administrator", "auditor"]); const rows = await env.DB.prepare("SELECT action, occurred_at as occurredAt, request_id as requestId, workspace_id as workspaceId, event_digest as eventDigest, previous_event_digest as previousEventDigest FROM organisation_audit_events WHERE organisation_id = ? ORDER BY occurred_at DESC LIMIT 500").bind(organisationId).all(); return json({ events: rows.results }, 200, requestId); }
    if (request.method === "GET" && tail === "usage") { const membership = await member(env, actor, organisationId); const organisation = await env.DB.prepare("SELECT plan_code as planCode, retention_days as retentionDays FROM organisations WHERE id = ?").bind(organisationId).first<{planCode:string;retentionDays:number}>(); const [workspaces, proofs] = await Promise.all([env.DB.prepare("SELECT count(*) as count FROM workspaces WHERE organisation_id = ? AND status != 'deleted'").bind(organisationId).first<{count:number}>(), env.DB.prepare("SELECT count(*) as count FROM workspace_proofs p JOIN workspaces w ON w.id = p.workspace_id WHERE w.organisation_id = ?").bind(organisationId).first<{count:number}>()]); return json({ plan: organisation?.planCode ?? 'pilot', retentionDays: organisation?.retentionDays ?? 0, usage: { workspaces: workspaces?.count ?? 0, proofs: proofs?.count ?? 0 }, permissions: { role: membership.role } }, 200, requestId); }
    return json({ error: "Not found." }, 404, requestId);
  } catch (cause) { return json({ error: cause instanceof Error ? cause.message : "Request failed.", requestId }, 403, requestId); }
}
